<a href="https://colab.research.google.com/github/AfsanaMim9639/Pytorch-For-Deep-Learning-Bootcamp/blob/main/00_pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)



2.6.0+cu124


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [3]:
## scaler
scaler=torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler.ndim

0

In [5]:
## Get tensor back as python int
scaler.item()

7

In [7]:
###Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [12]:
matrix=torch.tensor([[7,8],
                     [9,10]
                     ])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
matrix.shape

torch.Size([2, 2])

In [15]:
TENSOR=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [2,4,5]
                      ]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 4, 5]]])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [2, 4, 5]])

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR.ndim

3