<a href="https://colab.research.google.com/github/AfsanaMim9639/Pytorch-For-Deep-Learning-Bootcamp/blob/main/00_pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import torch
print(torch.__version__)



2.6.0+cu124


In [41]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [42]:
## scaler
scaler=torch.tensor(7)
scaler

tensor(7)

In [43]:
scaler.ndim

0

In [44]:
## Get tensor back as python int
scaler.item()

7

In [45]:
###Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [46]:
vector.ndim

1

In [47]:
vector.shape

torch.Size([2])

In [48]:
matrix=torch.tensor([[7,8],
                     [9,10]
                     ])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [49]:
matrix.shape

torch.Size([2, 2])

In [50]:
TENSOR=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [2,4,5]
                      ]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 4, 5]]])

In [51]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [2, 4, 5]])

In [52]:
TENSOR.shape

torch.Size([1, 3, 3])

In [53]:
TENSOR.ndim

3

## Random Tensor

Why Random Tensors??

--> Random Tensor are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

'Start with Random Numbers--> look at the data--> update random numbers-->look at data-->update random numbers '

In [54]:
## Create a random tensor of size(3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.2194, 0.7738, 0.2603, 0.3116],
        [0.2163, 0.9904, 0.9744, 0.6307],
        [0.4230, 0.7355, 0.2547, 0.2201]])

In [55]:
random_tensor.ndim

2

In [56]:
## Create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(224,224,3)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [57]:
torch.rand(3,3)

tensor([[0.6987, 0.0802, 0.8430],
        [0.5960, 0.3126, 0.2535],
        [0.3217, 0.8128, 0.6899]])

## Zeros and ones

In [58]:
## create a tensor of all tensor zeros
zeros=torch.zeros(size=(3,4))
zeros



tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [59]:
## create a tensor of all tensor ones
ones=torch.ones(size=(3,4))
ones



tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Creating a range of tensors and tensors-like

In [60]:
## Use torch.range ()
one_to_ten=torch.arange(start=0,end=11,step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
### Creating tensor like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor DataType

**Note:** Tensor datatype isone of the 3 big errors with Python & Deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [62]:
## Float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0], dtype=None,
                             device=None,
                             requires_grad=False
                             )

float_32_tensor

tensor([3., 6., 9.])

In [63]:
float_32_tensor.dtype

torch.float32

In [64]:
float_16_tensor=float_32_tensor.type(torch.float16)

In [65]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [66]:
int_32_tensor=torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [67]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Manipulating Tensors (tensor operation)

Tensor operations include:
* Addition
* Substraction
* Division
* Multiplication
* Matrix Multiplication

In [69]:
# Create a tensors and add 10 to it
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [70]:
# Multiply by 10
tensor * 10

tensor([10, 20, 30])

In [71]:
# Substraction by 10
tensor -10

tensor([-9, -8, -7])

In [72]:
# Try out Pytorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

## Matrix Multiplication
There are two ways of multiplication in neural network
1. elements wise multiplication
2. Matrix multiplication (dot products)

In [74]:
## Elements wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [76]:
## Matrix multiplication'
torch.matmul(tensor,tensor)

tensor(14)

In [77]:
tensor

tensor([1, 2, 3])

In [78]:
%%time
value=0
for i in range(len(tensor)):
  value+= tensor[i] + tensor[i]
print(value)

tensor(12)
CPU times: user 1.22 ms, sys: 0 ns, total: 1.22 ms
Wall time: 1.33 ms


In [79]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 281 µs, sys: 14 µs, total: 295 µs
Wall time: 205 µs


tensor(14)

### One of the most common errors in Deep Learning

In [81]:
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [4,5]
                       ])
tensor_B=torch.tensor([[10,20],
                       [30,40],
                       [40,50]
                       ])

torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [82]:
tensor_A.shape, tensor_B

(torch.Size([3, 2]),
 tensor([[10, 20],
         [30, 40],
         [40, 50]]))

### Finding the min,max,sum, etc (tensor aggregation)

In [83]:
## Create a tensor
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [85]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [86]:
torch.max(x),x.max()

(tensor(90), tensor(90))

### Finding the positional min and max

In [88]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [90]:
x.argmin()

tensor(0)

In [91]:
x[1]

tensor(10)

In [92]:
x.argmax()

tensor(9)

In [93]:
x[3]

tensor(30)